# Generated by Django 4.1 on 2022-09-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("VoterId", models.TextField(null=True)),
                ("VoterFirstName", models.TextField(null=True)),
                ("VoterMiddleName", models.TextField(null=True)),
                ("VoterLastName", models.TextField(null=True)),
                ("ResidenceStreetNumber", models.TextField(null=True)),
                ("ResidenceStreetName", models.TextField(null=True)),
                ("ResidenceApartment", models.TextField(null=True)),
                ("ResidenceCity", models.TextField(null=True)),
                ("ResidenceState", models.TextField(null=True)),
                ("ResidenceFullZip", models.TextField(null=True)),
                ("DobFormatted", models.TextField(null=True)),
                ("VoterSex", models.TextField(null=True)),
                ("VoterAreaCode", models.TextField(null=True)),
                ("VoterPhone", models.TextField(null=True)),
                ("VoterEMail", models.TextField(null=True)),
                ("VoterPartyCode", models.TextField(null=True)),
                ("MailingAddress1", models.TextField(null=True)),
                ("MailingCity", models.TextField(null=True)),
                ("MailingState", models.TextField(null=True)),
                ("MailingZip", models.TextField(null=True)),
            ],
        ),
    ]
