# Generated by Django 4.1 on 2022-09-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voters",
            name="RegistrationDateFormatted",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="voters",
            name="ResidenceStreetAddress",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="voters",
            name="VoterDistrictCode",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="voters",
            name="VoterStateLegislativeDistrictCode",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="voters",
            name="VoterTownCode",
            field=models.TextField(null=True),
        ),
    ]
